require "buildr"
require "buildr/scala"
REL = "com.thimbleware:scala-rel:jar:1.0-SNAPSHOT"

repositories.remote << "http://repo1.maven.org/maven2/"

define "databinder-dispatch-components" do
	scalac.with DATABINDER_DISPATCH, WICKET, EHCACHE
  scalac.options.deprecation = true
  scalac.options.other = "-unchecked"
	embed_server
end
