require "tasks/databinder.rb"

repositories.remote << "http://repo1.maven.org/maven2/"

define "databinder-dispatch-components" do
	compile.with DATABINDER_DISPATCH, WICKET, EHCACHE
  compile.options.deprecation = true
  compile.options.other = "-unchecked"
	embed_server
end
