require "buildr"
require "buildr/scala"
REL = "com.thimbleware:scala-rel:jar:1.0-SNAPSHOT"

repositories.remote << "http://repo1.maven.org/maven2/"

define "databinder-scouch" do
	scalac.with HTTPCLIENT
	embed_server
end
